### ISSUE TITLE
Failed to load plugin @babel/plugin-proposal-class

### ISSUE THREAD

**Issue by ugurkoysuren** [frimeio/EventIstanbul#1]
Bug in

`Error: Failed to load plugin @babel/plugin-proposal-class-properties: Cannot find module '@babel/eslint-plugin-plugin-proposal-class-properties'

Error: Failed to load plugin @babel/plugin-proposal-class-properties: Cannot find module '@babel/eslint-plugin-plugin-proposal-class-properties'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.load (D:\01_Development\EventIstanbul\node_modules\eslint\lib\config\plugins.js:134:29)
    at Array.forEach (<anonymous>)
    at Object.loadAll (D:\01_Development\EventIstanbul\node_modules\eslint\lib\config\plugins.js:162:21)
    at Object.load (D:\01_Development\EventIstanbul\node_modules\eslint\lib\config\config-file.js:541:21)
    at loadConfig (D:\01_Development\EventIstanbul\node_modules\eslint\lib\config.js:63:33)
    at getLocalConfig (D:\01_Development\EventIstanbul\node_modules\eslint\lib\config.js:130:29)
    at Config.getConfig (D:\01_Development\EventIstanbul\node_modules\eslint\lib\config.js:260:26)
    at processText (D:\01_Development\EventIstanbul\node_modules\eslint\lib\cli-engine.js:224:33)
Process finished with exit code -1`

**Comment by batuhandirek** [comment]
Fixed with #2, closing.
